<a href="https://colab.research.google.com/github/RajatVerma310795/hello-world/blob/master/iitk_pydata_RajatVerma_Day_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install numpy

In [0]:
# Python program to demonstrate 
# basic array characteristics 
import numpy as np 

# Creating array object 
arr = np.array( [[ 1, 2, 3], 
				[ 4, 2, 5],[2,7,9]] ) 

# Printing type of arr object 
print("Array is of type: ", type(arr)) 

# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

# Printing shape of array 
print("Shape of array: ", arr.shape) 

# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 

# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9
Array stores elements of type:  int64


In [0]:
import numpy
np_arr=np.arange(100000000)
%time z=np_arr*2

CPU times: user 144 ms, sys: 345 ms, total: 488 ms
Wall time: 488 ms


In [0]:

%%time 
for i in y:
  i*3

CPU times: user 757 ms, sys: 0 ns, total: 757 ms
Wall time: 759 ms


In [0]:
[i*2 for i in y]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [0]:
z=np.random.randn(3,3)
z

array([[ 0.29398499,  0.47896634, -0.5130209 ],
       [-0.35396747,  1.26434443, -2.15661099],
       [ 0.19012169, -0.35837929, -0.48202973]])

In [0]:
z.ndim

2

In [0]:
z.shape

(3, 3)

In [0]:
z.dtype

dtype('float64')

In [0]:
# Python program to demonstrate 
# basic array characteristics 
import numpy 

# Creating array object 
arr = numpy.array( [[ 1, 2, 3], 
				[ 4, 2, 5],[2,7,9]] ) 

# Printing type of arr object 
print("Array is of type: ", type(arr)) 

# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

# Printing shape of array 
print("Shape of array: ", arr.shape) 

# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 

# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (3, 3)
Size of array:  9
Array stores elements of type:  int64


In [0]:
np_arr=np.arange(100000000)

In [0]:
%time z=np_arr*2

CPU times: user 190 ms, sys: 1.3 ms, total: 192 ms
Wall time: 194 ms


In [0]:
np_arr=np.arange(100000000)

In [0]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [0]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Lo

<class 'bool'>
False
True
False
True


In [0]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


In [0]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [0]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [0]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [0]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


In [0]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


In [0]:
import numpy as np
np.ones((3,3),dtype=np.int16)
z=np.random.randn(3,3)
np.full((3,3),6)
np.ones_like(z)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
z=np.random.randint(0,2,(2,4))
z

array([[1, 0, 1, 1],
       [1, 1, 0, 1]])

In [0]:
np.random.seed(3)
z=np.random.randn(2,9)
z

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 , -0.2773882 ,
        -0.35475898, -0.08274148, -0.62700068, -0.04381817],
       [-0.47721803, -1.31386475,  0.88462238,  0.88131804,  1.70957306,
         0.05003364, -0.40467741, -0.54535995, -1.54647732]])

In [0]:
a=np.ones((3,3),dtype=np.int8)

In [0]:
b=a+a

In [0]:
b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int8)

In [0]:
a/3


array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [0]:
a/b

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [0]:
np.dot(a,b)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]], dtype=int8)

In [0]:
np.linalg.det(a)

0.0

In [0]:
a/3

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [0]:
a>4

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
c=a.copy()

In [0]:
c


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [0]:
c[:]=300000
c

array([[-32, -32, -32],
       [-32, -32, -32],
       [-32, -32, -32]], dtype=int8)

In [0]:
a=np.arange(100)

In [0]:
a[0:50].copy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [0]:
z=np.random.randint(0,10,(3,3,3))
z

array([[[7, 4, 3],
        [0, 0, 0],
        [0, 2, 2]],

       [[7, 0, 5],
        [0, 1, 4],
        [1, 2, 2]],

       [[4, 8, 0],
        [6, 0, 4],
        [1, 5, 1]]])

In [0]:
z[0,0]

array([7, 4, 3])

In [0]:
z[:2,:1]

array([[[7, 4, 3]],

       [[7, 0, 5]]])

In [0]:
z[2]
z[2,:]
z[2:,:]

array([[[4, 8, 0],
        [6, 0, 4],
        [1, 5, 1]]])

In [0]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[-1]

99

In [0]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [0]:
z=np.random.randn(10,3)
z

array([[ 1.2717041 ,  0.17594318, -0.70746362],
       [-0.63409305, -0.13368054, -1.3610901 ],
       [-1.30022534,  0.01004113, -1.05368742],
       [-0.91878414,  0.00852071,  1.01270555],
       [-1.87120247,  0.85779193, -0.93330128],
       [ 0.26973425, -0.91206319, -0.87171282],
       [-0.94458939, -0.84984818,  0.67813101],
       [-2.07581204, -1.09506468, -0.02420065],
       [-0.3690456 ,  0.47185781,  1.84699846],
       [-0.26119409,  1.27851999, -1.03967288]])

In [0]:
z.sum(axis=1)>0

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [0]:
z[z.sum(axis=1)>0]

array([[ 1.2717041 ,  0.17594318, -0.70746362],
       [-0.91878414,  0.00852071,  1.01270555],
       [-0.3690456 ,  0.47185781,  1.84699846]])

In [0]:
z[z<0]

array([-0.70746362, -0.63409305, -0.13368054, -1.3610901 , -1.30022534,
       -1.05368742, -0.91878414, -1.87120247, -0.93330128, -0.91206319,
       -0.87171282, -0.94458939, -0.84984818, -2.07581204, -1.09506468,
       -0.02420065, -0.3690456 , -0.26119409, -1.03967288])

In [0]:
z[z.sum(axis=-1)>0]

array([[ 1.2717041 ,  0.17594318, -0.70746362],
       [-0.91878414,  0.00852071,  1.01270555],
       [-0.3690456 ,  0.47185781,  1.84699846]])

In [0]:
mask=(z>0)&(z<0.5)
mask

array([[False,  True, False],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [0]:
z[mask]

array([0.17594318, 0.01004113, 0.00852071, 0.26973425, 0.47185781])

In [0]:
z[1]

array([-0.63409305, -0.13368054, -1.3610901 ])

In [0]:
z=np.random.randn(8,8,8)
z

array([[[-0.36337495, -0.19121804,  1.61115322, -0.5416413 ,
         -1.17096857,  0.42248754, -0.73910971,  1.33971843],
        [ 0.67446905,  0.63638934,  1.29883749,  0.66926649,
          1.40051026,  1.24630695,  0.53883581, -0.64360128],
        [ 0.84893186, -1.75729613,  0.00456386, -0.94778073,
          0.4914105 ,  0.87525777,  0.09446645, -1.05684084],
        [ 0.36356378,  1.06718518, -0.30516134,  1.12096088,
          0.35108312,  0.42251646,  0.31367575, -0.57419381],
        [ 0.44024233,  1.07753417, -1.07128983, -0.55406848,
         -0.42398774,  0.05950704,  0.56167223, -1.00860758],
        [ 0.26309463,  0.4975868 ,  0.823931  , -0.13616535,
         -0.72072876,  0.64677019,  0.34625452, -0.23428083],
        [-0.52098461,  1.54875979,  0.0611088 , -0.67940978,
          0.26484372,  1.0403459 ,  0.11415177,  0.93787246],
        [ 0.40247483,  1.03597266,  0.79376553, -1.40136672,
          0.24213856,  0.04860006,  1.18331952,  1.94485739]],

       [[-0.99

In [0]:
import numpy as np
x = np.array([[[-0.36337495, -0.19121804,  1.61115322, -0.5416413 ,
         -1.17096857,  0.42248754, -0.73910971,  1.33971843],
        [ 0.67446905,  0.63638934,  1.29883749,  0.66926649,
          1.40051026,  1.24630695,  0.53883581, -0.64360128],
        [ 0.84893186, -1.75729613,  0.00456386, -0.94778073,
          0.4914105 ,  0.87525777,  0.09446645, -1.05684084],
        [ 0.36356378,  1.06718518, -0.30516134,  1.12096088,
          0.35108312,  0.42251646,  0.31367575, -0.57419381],
        [ 0.44024233,  1.07753417, -1.07128983, -0.55406848,
         -0.42398774,  0.05950704,  0.56167223, -1.00860758],
        [ 0.26309463,  0.4975868 ,  0.823931  , -0.13616535,
         -0.72072876,  0.64677019,  0.34625452, -0.23428083],
        [-0.52098461,  1.54875979,  0.0611088 , -0.67940978,
          0.26484372,  1.0403459 ,  0.11415177,  0.93787246],
        [ 0.40247483,  1.03597266,  0.79376553, -1.40136672,
          0.24213856,  0.04860006,  1.18331952,  1.94485739]],

       [[-0.9999224 ,  1.17590429,  1.58384074, -1.88016542,
          0.55834079, -0.89949773, -2.1953908 , -1.25755975],
        [ 0.81471034,  1.41554604, -1.16331935, -0.31705147,
         -1.3345472 , -0.7479962 ,  0.49671964,  0.11692332],
        [ 0.29044969,  0.88502348,  0.70158126,  0.30112693,
         -0.09875765,  2.00822099, -0.82441293,  0.79159882],
        [-3.25276871,  2.35901762,  1.02167002,  1.89077767,
         -0.17283299, -0.70853195, -1.57593459, -1.11076945],
        [ 2.43040943,  1.98874102,  1.77740184,  0.31471795,
          1.70149606, -1.52641823, -0.08731125, -0.4693424 ],
        [-0.42270016,  0.87498303, -0.24808544, -0.6524692 ,
          0.07342193,  0.00586369,  0.51512488, -0.40980525],
        [-0.05019831,  1.0235694 ,  0.72601163, -0.73969414,
         -1.7537552 , -1.78267144,  1.69978399,  0.16633242],
        [-0.21791978,  1.26224101, -1.84870898, -0.09361026,
         -2.21959579, -0.7076975 ,  0.87148664,  0.26469188]],

       [[-0.07765079,  0.0345471 , -0.85472517,  1.450707  ,
          0.73630804,  0.10912708, -0.17397987,  1.58404021],
        [ 0.01652522, -0.60639438, -0.64193368,  0.25942132,
         -0.66659278, -0.47110043,  0.57679756,  0.05724659],
        [ 1.76553668,  0.42336351, -0.77268396,  1.09818686,
          0.05368668, -0.79096824,  0.35891104, -1.20128779],
        [ 1.91025799,  0.58830534,  1.0309888 ,  0.7834406 ,
         -0.33897052, -1.59642927, -1.1215477 , -1.20230036],
        [ 0.22853806, -0.08813633, -2.02840457,  0.8137258 ,
          0.33627294, -1.02056063,  0.09155003,  3.08886513],
        [ 0.48954752, -1.00011911, -1.65739184,  0.60533885,
         -0.17938676,  1.19744564, -0.05179905,  1.11401143],
        [-0.50746205, -0.83929431, -1.24447907,  0.60720431,
         -0.35608491,  0.27803339,  1.45075673,  1.05029458],
        [-0.73695754,  0.26796357, -0.38696815, -0.16587332,
          0.40489049,  0.88248063,  0.13880528, -0.60322656]],

       [[ 1.55279804, -0.28391667, -0.46668277,  0.70527379,
          0.33729411, -0.20748492,  2.6305343 ,  2.1886117 ],
        [ 0.56110228,  0.34450235, -0.7680492 ,  0.27979905,
         -0.3610866 ,  1.772109  , -1.63381594, -0.95618371],
        [ 1.1054027 , -0.07542821, -0.10850534,  0.22033672,
         -0.02651276,  1.21851074, -0.91445025, -0.86040433],
        [-1.13213743,  1.72494032, -0.23604904,  1.22000578,
          0.15306064,  1.23443046,  0.25061267,  0.35455878],
        [-0.73494846, -0.47288589,  0.49817005,  0.70544569,
         -0.1678933 , -0.91120997, -0.64866917,  1.8707832 ],
        [ 0.81543354, -0.41616178, -0.70779625,  0.46885584,
          0.57509448, -0.87186731, -0.69040733,  1.89436534],
        [ 0.71843776, -0.00479409,  1.52846396, -0.62702111,
          1.65393707, -0.06921595, -0.48749483, -0.76496497],
        [-1.19186012,  0.64133005,  0.57110375, -1.41238558,
         -0.20194892,  0.86534528, -0.44820377, -1.03157782]],

       [[-0.37169487, -0.60670082, -0.08217115,  2.13978352,
         -0.66776766,  0.3096136 , -0.17640316,  0.75972311],
        [ 0.68803158, -0.01749208, -1.09546578, -0.09923184,
         -0.81965673, -0.40953328,  0.88487127,  0.42671478],
        [-0.68485856, -0.63549841,  0.39631292, -0.43309704,
         -1.48669892, -0.43769912, -0.21168882,  0.42814002],
        [ 0.51748683,  0.59524486, -0.68714554,  2.20128565,
          0.44015893, -0.09445714,  0.7040363 ,  0.23659022],
        [-2.29931124,  1.18426827, -0.21885241, -1.47192856,
          0.03409908,  0.67508248,  1.62303855,  0.99415627],
        [ 0.66801546,  0.66965841,  1.09986398, -2.59776937,
          1.23635842, -0.18333878,  0.10265375,  0.69760225],
        [ 0.38795999,  0.9464399 ,  1.52599296,  0.77788031,
         -0.06586459, -1.65681846, -0.0908898 ,  0.88940213],
        [-2.00502436, -0.10922257,  0.50868888,  0.86469114,
          1.17830511,  1.18964849,  0.1169976 , -0.21275078]],

       [[ 0.01767338, -0.81945681, -0.40892072, -0.53749856,
          0.08168593, -0.89171152,  2.37348366,  0.04409203],
        [ 0.13913591,  0.51321328, -1.08376693,  0.33096317,
         -1.14103887, -2.01325719,  0.51668939, -2.84832889],
        [ 1.4129704 , -0.92525347, -0.6453766 ,  0.68522758,
          0.03131367, -0.46162143, -1.27124744,  0.4153572 ],
        [ 1.23381012,  1.6863634 , -0.15390508,  0.10693391,
         -2.14823988,  0.77199668,  0.55110515, -0.11387667],
        [ 0.31687054, -0.81740667, -0.96464585,  0.71527462,
          0.89933803, -0.48189178, -0.48778638,  1.06112923],
        [ 0.14866407,  2.36802607,  0.82435356, -0.70566229,
          0.02882325, -0.36668337,  0.09833968,  0.48514864],
        [-1.03096173, -0.62335341,  0.07595689,  0.49099691,
         -0.89083478, -2.13574804,  0.64916785, -0.21457675],
        [ 0.94125089, -0.55449324, -0.19988925,  0.97279036,
          1.94446016,  0.72757272, -0.36140076,  0.95048376]],

       [[ 1.08464023, -1.43503022, -0.79268175,  0.15833147,
         -1.00942184, -0.20671899,  3.02758132, -0.77227674],
        [-0.16117183, -2.26982722, -0.80643034,  0.44940424,
         -0.28004538, -1.9367436 ,  1.29504237,  0.80607537],
        [-0.31447784, -1.86829879, -0.57359464, -0.36466995,
          0.44944582,  1.1431109 ,  0.87503997, -0.69844446],
        [-0.28845718,  0.48023546,  0.46116078,  0.04303454,
          0.08851692,  0.70143801, -2.12962006,  0.0483929 ],
        [-0.01298483, -0.42451359, -0.34897219, -0.40097738,
          2.48541712,  0.217042  , -0.4066374 , -0.94632225],
        [-0.08000587, -0.24372851,  0.01553562,  0.13007874,
          0.85210397,  0.15591757,  0.40225916,  1.69046415],
        [-0.16962411,  1.6228357 , -0.00882255, -1.15471855,
          0.47547434,  0.76355535,  1.6454398 , -0.44044622],
        [-0.46917485, -0.30881452,  0.51917242,  0.62891035,
          0.43171502, -1.17627572,  0.54626833,  1.54324932]],

       [[ 0.2631188 , -2.10952914, -0.59939373,  0.99869393,
          1.96251543,  1.19640179, -0.52179783, -0.64003623],
        [ 0.59314603,  0.71623818,  0.26067409, -1.07240095,
         -1.10854336, -0.50157224,  0.53363211,  0.32696387],
        [-2.4429711 , -0.33434927,  0.35477733, -0.2799178 ,
         -1.83213787, -1.05275551,  0.45385477, -0.84172092],
        [-0.90037698,  2.61832794,  0.96116408,  0.00863791,
          0.44594695, -0.10289984, -1.11961556,  0.61325739],
        [-0.19511801,  1.56005075, -1.10266249, -2.06639657,
          0.74513269, -0.06719751, -1.67425664, -0.27470891],
        [ 0.24131049,  0.32691232, -0.95188948,  2.33751429,
          0.61678244,  0.30155079,  0.65149343, -0.69018639],
        [ 1.05807557,  2.11345856, -0.29919458,  0.06942353,
          1.2342043 ,  1.59519001,  0.38052   , -0.4358339 ],
        [-0.54211133, -0.13275926, -0.68634396, -0.5897906 ,
          0.33063317,  1.12675884, -1.66919356, -0.78223456]]])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x>3] = 0
x[x<8] = 0
print(x)

Original array:
[[[-0.36337495 -0.19121804  1.61115322 -0.5416413  -1.17096857
    0.42248754 -0.73910971  1.33971843]
  [ 0.67446905  0.63638934  1.29883749  0.66926649  1.40051026
    1.24630695  0.53883581 -0.64360128]
  [ 0.84893186 -1.75729613  0.00456386 -0.94778073  0.4914105
    0.87525777  0.09446645 -1.05684084]
  [ 0.36356378  1.06718518 -0.30516134  1.12096088  0.35108312
    0.42251646  0.31367575 -0.57419381]
  [ 0.44024233  1.07753417 -1.07128983 -0.55406848 -0.42398774
    0.05950704  0.56167223 -1.00860758]
  [ 0.26309463  0.4975868   0.823931   -0.13616535 -0.72072876
    0.64677019  0.34625452 -0.23428083]
  [-0.52098461  1.54875979  0.0611088  -0.67940978  0.26484372
    1.0403459   0.11415177  0.93787246]
  [ 0.40247483  1.03597266  0.79376553 -1.40136672  0.24213856
    0.04860006  1.18331952  1.94485739]]

 [[-0.9999224   1.17590429  1.58384074 -1.88016542  0.55834079
   -0.89949773 -2.1953908  -1.25755975]
  [ 0.81471034  1.41554604 -1.16331935 -0.31705147 -1.33

In [0]:
import numpy as geek 

in_arr = geek.array([[[-0.36337495, -0.19121804,  1.61115322, -0.5416413 ,
         -1.17096857,  0.42248754, -0.73910971,  1.33971843],
        [ 0.67446905,  0.63638934,  1.29883749,  0.66926649,
          1.40051026,  1.24630695,  0.53883581, -0.64360128],
        [ 0.84893186, -1.75729613,  0.00456386, -0.94778073,
          0.4914105 ,  0.87525777,  0.09446645, -1.05684084],
        [ 0.36356378,  1.06718518, -0.30516134,  1.12096088,
          0.35108312,  0.42251646,  0.31367575, -0.57419381],
        [ 0.44024233,  1.07753417, -1.07128983, -0.55406848,
         -0.42398774,  0.05950704,  0.56167223, -1.00860758],
        [ 0.26309463,  0.4975868 ,  0.823931  , -0.13616535,
         -0.72072876,  0.64677019,  0.34625452, -0.23428083],
        [-0.52098461,  1.54875979,  0.0611088 , -0.67940978,
          0.26484372,  1.0403459 ,  0.11415177,  0.93787246],
        [ 0.40247483,  1.03597266,  0.79376553, -1.40136672,
          0.24213856,  0.04860006,  1.18331952,  1.94485739]],

       [[-0.9999224 ,  1.17590429,  1.58384074, -1.88016542,
          0.55834079, -0.89949773, -2.1953908 , -1.25755975],
        [ 0.81471034,  1.41554604, -1.16331935, -0.31705147,
         -1.3345472 , -0.7479962 ,  0.49671964,  0.11692332],
        [ 0.29044969,  0.88502348,  0.70158126,  0.30112693,
         -0.09875765,  2.00822099, -0.82441293,  0.79159882],
        [-3.25276871,  2.35901762,  1.02167002,  1.89077767,
         -0.17283299, -0.70853195, -1.57593459, -1.11076945],
        [ 2.43040943,  1.98874102,  1.77740184,  0.31471795,
          1.70149606, -1.52641823, -0.08731125, -0.4693424 ],
        [-0.42270016,  0.87498303, -0.24808544, -0.6524692 ,
          0.07342193,  0.00586369,  0.51512488, -0.40980525],
        [-0.05019831,  1.0235694 ,  0.72601163, -0.73969414,
         -1.7537552 , -1.78267144,  1.69978399,  0.16633242],
        [-0.21791978,  1.26224101, -1.84870898, -0.09361026,
         -2.21959579, -0.7076975 ,  0.87148664,  0.26469188]],

       [[-0.07765079,  0.0345471 , -0.85472517,  1.450707  ,
          0.73630804,  0.10912708, -0.17397987,  1.58404021],
        [ 0.01652522, -0.60639438, -0.64193368,  0.25942132,
         -0.66659278, -0.47110043,  0.57679756,  0.05724659],
        [ 1.76553668,  0.42336351, -0.77268396,  1.09818686,
          0.05368668, -0.79096824,  0.35891104, -1.20128779],
        [ 1.91025799,  0.58830534,  1.0309888 ,  0.7834406 ,
         -0.33897052, -1.59642927, -1.1215477 , -1.20230036],
        [ 0.22853806, -0.08813633, -2.02840457,  0.8137258 ,
          0.33627294, -1.02056063,  0.09155003,  3.08886513],
        [ 0.48954752, -1.00011911, -1.65739184,  0.60533885,
         -0.17938676,  1.19744564, -0.05179905,  1.11401143],
        [-0.50746205, -0.83929431, -1.24447907,  0.60720431,
         -0.35608491,  0.27803339,  1.45075673,  1.05029458],
        [-0.73695754,  0.26796357, -0.38696815, -0.16587332,
          0.40489049,  0.88248063,  0.13880528, -0.60322656]],

       [[ 1.55279804, -0.28391667, -0.46668277,  0.70527379,
          0.33729411, -0.20748492,  2.6305343 ,  2.1886117 ],
        [ 0.56110228,  0.34450235, -0.7680492 ,  0.27979905,
         -0.3610866 ,  1.772109  , -1.63381594, -0.95618371],
        [ 1.1054027 , -0.07542821, -0.10850534,  0.22033672,
         -0.02651276,  1.21851074, -0.91445025, -0.86040433],
        [-1.13213743,  1.72494032, -0.23604904,  1.22000578,
          0.15306064,  1.23443046,  0.25061267,  0.35455878],
        [-0.73494846, -0.47288589,  0.49817005,  0.70544569,
         -0.1678933 , -0.91120997, -0.64866917,  1.8707832 ],
        [ 0.81543354, -0.41616178, -0.70779625,  0.46885584,
          0.57509448, -0.87186731, -0.69040733,  1.89436534],
        [ 0.71843776, -0.00479409,  1.52846396, -0.62702111,
          1.65393707, -0.06921595, -0.48749483, -0.76496497],
        [-1.19186012,  0.64133005,  0.57110375, -1.41238558,
         -0.20194892,  0.86534528, -0.44820377, -1.03157782]],

       [[-0.37169487, -0.60670082, -0.08217115,  2.13978352,
         -0.66776766,  0.3096136 , -0.17640316,  0.75972311],
        [ 0.68803158, -0.01749208, -1.09546578, -0.09923184,
         -0.81965673, -0.40953328,  0.88487127,  0.42671478],
        [-0.68485856, -0.63549841,  0.39631292, -0.43309704,
         -1.48669892, -0.43769912, -0.21168882,  0.42814002],
        [ 0.51748683,  0.59524486, -0.68714554,  2.20128565,
          0.44015893, -0.09445714,  0.7040363 ,  0.23659022],
        [-2.29931124,  1.18426827, -0.21885241, -1.47192856,
          0.03409908,  0.67508248,  1.62303855,  0.99415627],
        [ 0.66801546,  0.66965841,  1.09986398, -2.59776937,
          1.23635842, -0.18333878,  0.10265375,  0.69760225],
        [ 0.38795999,  0.9464399 ,  1.52599296,  0.77788031,
         -0.06586459, -1.65681846, -0.0908898 ,  0.88940213],
        [-2.00502436, -0.10922257,  0.50868888,  0.86469114,
          1.17830511,  1.18964849,  0.1169976 , -0.21275078]],

       [[ 0.01767338, -0.81945681, -0.40892072, -0.53749856,
          0.08168593, -0.89171152,  2.37348366,  0.04409203],
        [ 0.13913591,  0.51321328, -1.08376693,  0.33096317,
         -1.14103887, -2.01325719,  0.51668939, -2.84832889],
        [ 1.4129704 , -0.92525347, -0.6453766 ,  0.68522758,
          0.03131367, -0.46162143, -1.27124744,  0.4153572 ],
        [ 1.23381012,  1.6863634 , -0.15390508,  0.10693391,
         -2.14823988,  0.77199668,  0.55110515, -0.11387667],
        [ 0.31687054, -0.81740667, -0.96464585,  0.71527462,
          0.89933803, -0.48189178, -0.48778638,  1.06112923],
        [ 0.14866407,  2.36802607,  0.82435356, -0.70566229,
          0.02882325, -0.36668337,  0.09833968,  0.48514864],
        [-1.03096173, -0.62335341,  0.07595689,  0.49099691,
         -0.89083478, -2.13574804,  0.64916785, -0.21457675],
        [ 0.94125089, -0.55449324, -0.19988925,  0.97279036,
          1.94446016,  0.72757272, -0.36140076,  0.95048376]],

       [[ 1.08464023, -1.43503022, -0.79268175,  0.15833147,
         -1.00942184, -0.20671899,  3.02758132, -0.77227674],
        [-0.16117183, -2.26982722, -0.80643034,  0.44940424,
         -0.28004538, -1.9367436 ,  1.29504237,  0.80607537],
        [-0.31447784, -1.86829879, -0.57359464, -0.36466995,
          0.44944582,  1.1431109 ,  0.87503997, -0.69844446],
        [-0.28845718,  0.48023546,  0.46116078,  0.04303454,
          0.08851692,  0.70143801, -2.12962006,  0.0483929 ],
        [-0.01298483, -0.42451359, -0.34897219, -0.40097738,
          2.48541712,  0.217042  , -0.4066374 , -0.94632225],
        [-0.08000587, -0.24372851,  0.01553562,  0.13007874,
          0.85210397,  0.15591757,  0.40225916,  1.69046415],
        [-0.16962411,  1.6228357 , -0.00882255, -1.15471855,
          0.47547434,  0.76355535,  1.6454398 , -0.44044622],
        [-0.46917485, -0.30881452,  0.51917242,  0.62891035,
          0.43171502, -1.17627572,  0.54626833,  1.54324932]],

       [[ 0.2631188 , -2.10952914, -0.59939373,  0.99869393,
          1.96251543,  1.19640179, -0.52179783, -0.64003623],
        [ 0.59314603,  0.71623818,  0.26067409, -1.07240095,
         -1.10854336, -0.50157224,  0.53363211,  0.32696387],
        [-2.4429711 , -0.33434927,  0.35477733, -0.2799178 ,
         -1.83213787, -1.05275551,  0.45385477, -0.84172092],
        [-0.90037698,  2.61832794,  0.96116408,  0.00863791,
          0.44594695, -0.10289984, -1.11961556,  0.61325739],
        [-0.19511801,  1.56005075, -1.10266249, -2.06639657,
          0.74513269, -0.06719751, -1.67425664, -0.27470891],
        [ 0.24131049,  0.32691232, -0.95188948,  2.33751429,
          0.61678244,  0.30155079,  0.65149343, -0.69018639],
        [ 1.05807557,  2.11345856, -0.29919458,  0.06942353,
          1.2342043 ,  1.59519001,  0.38052   , -0.4358339 ],
        [-0.54211133, -0.13275926, -0.68634396, -0.5897906 ,
          0.33063317,  1.12675884, -1.66919356, -0.78223456]]]) 
   
print ("Input array : ", in_arr)  
mask=(x>3)&(x<8)
    
out_arr = geek.negative(in_arr)  
print ("negative of array elements: ", out_arr)

Input array :  [[[-0.36337495 -0.19121804  1.61115322 -0.5416413  -1.17096857
    0.42248754 -0.73910971  1.33971843]
  [ 0.67446905  0.63638934  1.29883749  0.66926649  1.40051026
    1.24630695  0.53883581 -0.64360128]
  [ 0.84893186 -1.75729613  0.00456386 -0.94778073  0.4914105
    0.87525777  0.09446645 -1.05684084]
  [ 0.36356378  1.06718518 -0.30516134  1.12096088  0.35108312
    0.42251646  0.31367575 -0.57419381]
  [ 0.44024233  1.07753417 -1.07128983 -0.55406848 -0.42398774
    0.05950704  0.56167223 -1.00860758]
  [ 0.26309463  0.4975868   0.823931   -0.13616535 -0.72072876
    0.64677019  0.34625452 -0.23428083]
  [-0.52098461  1.54875979  0.0611088  -0.67940978  0.26484372
    1.0403459   0.11415177  0.93787246]
  [ 0.40247483  1.03597266  0.79376553 -1.40136672  0.24213856
    0.04860006  1.18331952  1.94485739]]

 [[-0.9999224   1.17590429  1.58384074 -1.88016542  0.55834079
   -0.89949773 -2.1953908  -1.25755975]
  [ 0.81471034  1.41554604 -1.16331935 -0.31705147 -1.334

In [0]:
x=np.random.randn(8,8,8)
x
mask=(x>3) & (x<8)
x[mask]=-1*x[mask]
x

array([[[-0.67329826, -0.27328512, -0.57828259,  1.53097671,
         -0.33991696, -0.7569066 ,  0.8692644 , -1.15208764],
        [ 2.22902263, -0.02659195,  0.09374366,  0.86882975,
          0.66857157, -0.95348756,  1.51831909, -0.81379266],
        [-0.18404581, -1.31687711,  0.23308455, -1.38851181,
         -1.11682408, -0.85585058,  1.50198391, -2.04508616],
        [ 1.61286333,  0.91318976,  1.19986974, -1.3852791 ,
         -0.42789323, -0.0585903 ,  1.10341019,  1.08773922],
        [ 0.96705266, -0.5688494 ,  0.46934441, -1.58379068,
          1.61212554, -1.73095033, -0.90167185,  0.2819462 ],
        [-0.31101262,  0.36151241, -0.30089407,  0.37851558,
          0.53100794,  0.73655268,  0.28629076,  0.62012878],
        [-0.25468138, -0.16176903, -0.49715436,  0.408628  ,
          0.16505657,  0.96180731,  1.01275549, -0.81933812],
        [ 0.39014155,  0.28054823,  0.31417537, -0.95820415,
          1.63677442, -0.62508459,  1.01889478, -0.11303677]],

       [[ 0.37

In [0]:
x=np.random.randn(8,3)
x


array([[-0.61234927, -0.52860551,  2.48884939],
       [ 0.27694122, -0.05947791, -2.14921002],
       [-0.80644867,  0.27000106,  2.05114224],
       [ 0.21692715, -0.81704647, -1.02490133],
       [-1.71352952, -1.08086386, -0.43342636],
       [ 0.29925502, -2.30710414, -0.82023614],
       [-1.83315086,  0.25427734, -1.0719684 ],
       [ 1.03243741,  1.81837   , -0.00610129]])

In [0]:
# We need install numpy in order to import it 
import numpy as np 
  
# input two matrices 
x = ([[-0.61234927, -0.52860551,  2.48884939],
       [ 0.27694122, -0.05947791, -2.14921002],
       [-0.80644867,  0.27000106,  2.05114224],
       [ 0.21692715, -0.81704647, -1.02490133],
       [-1.71352952, -1.08086386, -0.43342636],
       [ 0.29925502, -2.30710414, -0.82023614],
       [-1.83315086,  0.25427734, -1.0719684 ],
       [ 1.03243741,  1.81837   , -0.00610129]]) 
y = ([[-1.00866137, -0.93622685],
       [ 0.7739149 , -0.05289863],
       [-0.49613763,  0.76658735]]) 
  
# This will return dot product 
res = np.dot(x,y) 
  
# print resulted matrix 
print(res) 

[[-1.02625446  2.50918079]
 [ 0.74093321 -1.90369072]
 [ 0.00474261  2.31311591]
 [-0.34263836 -0.94554878]
 [ 1.10691351  1.3291694 ]
 [-1.68039923 -0.78691059]
 [ 2.57766134  0.88103672]
 [ 0.36891098 -1.06746208]]


In [0]:
res.flatten()

array([-1.02625446,  2.50918079,  0.74093321, -1.90369072,  0.00474261,
        2.31311591, -0.34263836, -0.94554878,  1.10691351,  1.3291694 ,
       -1.68039923, -0.78691059,  2.57766134,  0.88103672,  0.36891098,
       -1.06746208])

In [0]:
y=np.random.randn(3,2)
y


array([[-1.00866137, -0.93622685],
       [ 0.7739149 , -0.05289863],
       [-0.49613763,  0.76658735]])

In [0]:
z=np.random.randn(3,4)
z

array([[-0.53535331, -1.05531933, -0.08977706,  0.946931  ],
       [-0.68859598,  0.77074928, -2.45447165, -1.15539802],
       [ 0.88598206, -0.8930227 , -0.56815816,  0.57511049]])

In [0]:
z.T

array([[-0.53535331, -0.68859598,  0.88598206],
       [-1.05531933,  0.77074928, -0.8930227 ],
       [-0.08977706, -2.45447165, -0.56815816],
       [ 0.946931  , -1.15539802,  0.57511049]])

In [0]:
z=np.arange(16)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
np.sqrt(z)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [0]:
arr=np.random.randn(7)*5

In [0]:
arr

array([ 0.2182991 ,  3.16870133, -1.3112656 ,  2.65382176, -2.98275199,
        9.35468538, -7.90807822])

In [0]:
np.square(z)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [0]:
np.add(z,z)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [0]:
np.exp(z)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [0]:
np.log(z)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [0]:
np.sign(z)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
np.cos(z)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791])

In [0]:
np.sin(z)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [0]:
np.power(z,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [0]:
np.power(z,9)

array([          0,           1,         512,       19683,      262144,
           1953125,    10077696,    40353607,   134217728,   387420489,
        1000000000,  2357947691,  5159780352, 10604499373, 20661046784,
       38443359375])

In [0]:
np.logical_or(z,z)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [0]:
def MonteCarloPi(maxIterations):
#Draw a square and a circle to frame out simulation
    squareX = [1,-1,-1,1,1]
    squareY = [1,1,-1,-1,1]
    circleX,circleY = [],[]
    
    for i in range(361):
        circleX.append(np.cos(np.pi*i/180))
        circleY.append(np.sin(np.pi*i/180))

#Start keeping track of values we're interested in
    insideX,insideY,outsideX,outsideY,Iteration,CurrentPi = [],[],[],[],[],[]
    insideCounter = 0

#Generate a bunch of values of x and y between -1 and 1, then assess their combined radius on an xy plane
    for i in range(maxIterations):
        x = 2*(random()-0.5)
        y = 2*(random()-0.5)
        r = np.sqrt(x**2+y**2)
        Iteration.append(i)
        if r <= 1:
            insideCounter +=1
            insideX.append(x)
            insideY.append(y)
        else:
            outsideX.append(x)
            outsideY.append(y)
        CurrentPi.append(4*insideCounter/(i+1))

    piValue = 4*insideCounter / maxIterations
    piError = round(100*((piValue-pi)/pi),4)

#Draw a 2D plot of where our iterations landed compared to the square and circle
    rcParams['figure.figsize'] = 5, 5
    plt.plot(squareX,squareY,color='#000000')
    plt.plot(circleX,circleY,color='#0000CC')
    plt.scatter(insideX,insideY,color='#00CC00',marker=".")
    plt.scatter(outsideX,outsideY,color='#CC0000',marker=".")
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
    
#Draw a psuedo-time series plot of current estimate of pi vs. iteration number
    plt.plot(Iteration,CurrentPi,color='#009900')
    plt.axhline(y=pi,color='#0F0F0F',ls='--')
    plt.axis([0,maxIterations,0,4.1])
    plt.xlabel('Iteration Number')
    plt.ylabel('Estimate for pi')
    plt.show()

#print out our final estimate and how it compares to the true value
    print('\n' + f'Pi is approximately {piValue}\n')
    print(f'This is {piError}% off the true value.\n')


In [0]:
def pClosest(points, K): 
  
    points.sort(key = lambda K: K[0]**2 + K[1]**2) 
  
    return points[:K] 
  
# Driver program 
points = [-0.36337495, -0.19121804],[1.61115322, -0.5416413] ,
         [-1.17096857,  0.42248754, -0.73910971,  1.33971843],
        [ 0.67446905,  0.63638934,  1.29883749,  0.66926649,
          1.40051026,  1.24630695,  0.53883581, -0.64360128],
        [ 0.84893186, -1.75729613,  0.00456386, -0.94778073,
          0.4914105 ,  0.87525777,  0.09446645, -1.05684084],
        [ 0.36356378,  1.06718518, -0.30516134,  1.12096088,
          0.35108312,  0.42251646,  0.31367575, -0.57419381],
        [ 0.44024233,  1.07753417, -1.07128983, -0.55406848,
         -0.42398774,  0.05950704,  0.56167223, -1.00860758],
        [ 0.26309463,  0.4975868 ,  0.823931  , -0.13616535,
         -0.72072876,  0.64677019,  0.34625452, -0.23428083],
        [-0.52098461,  1.54875979,  0.0611088 , -0.67940978,
          0.26484372,  1.0403459 ,  0.11415177,  0.93787246],
        [ 0.40247483,  1.03597266,  0.79376553, -1.40136672,
          0.24213856,  0.04860006,  1.18331952,  1.94485739]],

       [[-0.9999224 ,  1.17590429,  1.58384074, -1.88016542,
          0.55834079, -0.89949773, -2.1953908 , -1.25755975],
        [ 0.81471034,  1.41554604, -1.16331935, -0.31705147,
         -1.3345472 , -0.7479962 ,  0.49671964,  0.11692332],
        [ 0.29044969,  0.88502348,  0.70158126,  0.30112693,
         -0.09875765,  2.00822099, -0.82441293,  0.79159882],
        [-3.25276871,  2.35901762,  1.02167002,  1.89077767,
         -0.17283299, -0.70853195, -1.57593459, -1.11076945],
        [ 2.43040943,  1.98874102,  1.77740184,  0.31471795,
          1.70149606, -1.52641823, -0.08731125, -0.4693424 ],
        [-0.42270016,  0.87498303, -0.24808544, -0.6524692 ,
          0.07342193,  0.00586369,  0.51512488, -0.40980525],
        [-0.05019831,  1.0235694 ,  0.72601163, -0.73969414,
         -1.7537552 , -1.78267144,  1.69978399,  0.16633242],
        [-0.21791978,  1.26224101, -1.84870898, -0.09361026,
         -2.21959579, -0.7076975 ,  0.87148664,  0.26469188]],

       [[-0.07765079,  0.0345471 , -0.85472517,  1.450707  ,
          0.73630804,  0.10912708, -0.17397987,  1.58404021],
        [ 0.01652522, -0.60639438, -0.64193368,  0.25942132,
         -0.66659278, -0.47110043,  0.57679756,  0.05724659],
        [ 1.76553668,  0.42336351, -0.77268396,  1.09818686,
          0.05368668, -0.79096824,  0.35891104, -1.20128779],
        [ 1.91025799,  0.58830534,  1.0309888 ,  0.7834406 ,
         -0.33897052, -1.59642927, -1.1215477 , -1.20230036],
        [ 0.22853806, -0.08813633, -2.02840457,  0.8137258 ,
          0.33627294, -1.02056063,  0.09155003,  3.08886513],
        [ 0.48954752, -1.00011911, -1.65739184,  0.60533885,
         -0.17938676,  1.19744564, -0.05179905,  1.11401143],
        [-0.50746205, -0.83929431, -1.24447907,  0.60720431,
         -0.35608491,  0.27803339,  1.45075673,  1.05029458],
        [-0.73695754,  0.26796357, -0.38696815, -0.16587332,
          0.40489049,  0.88248063,  0.13880528, -0.60322656]],

       [[ 1.55279804, -0.28391667, -0.46668277,  0.70527379,
          0.33729411, -0.20748492,  2.6305343 ,  2.1886117 ],
        [ 0.56110228,  0.34450235, -0.7680492 ,  0.27979905,
         -0.3610866 ,  1.772109  , -1.63381594, -0.95618371],
        [ 1.1054027 , -0.07542821, -0.10850534,  0.22033672,
         -0.02651276,  1.21851074, -0.91445025, -0.86040433],
        [-1.13213743,  1.72494032, -0.23604904,  1.22000578,
          0.15306064,  1.23443046,  0.25061267,  0.35455878],
        [-0.73494846, -0.47288589,  0.49817005,  0.70544569,
         -0.1678933 , -0.91120997, -0.64866917,  1.8707832 ],
        [ 0.81543354, -0.41616178, -0.70779625,  0.46885584,
          0.57509448, -0.87186731, -0.69040733,  1.89436534],
        [ 0.71843776, -0.00479409,  1.52846396, -0.62702111,
          1.65393707, -0.06921595, -0.48749483, -0.76496497],
        [-1.19186012,  0.64133005,  0.57110375, -1.41238558,
         -0.20194892,  0.86534528, -0.44820377, -1.03157782]],

       [[-0.37169487, -0.60670082, -0.08217115,  2.13978352,
         -0.66776766,  0.3096136 , -0.17640316,  0.75972311],
        [ 0.68803158, -0.01749208, -1.09546578, -0.09923184,
         -0.81965673, -0.40953328,  0.88487127,  0.42671478],
        [-0.68485856, -0.63549841,  0.39631292, -0.43309704,
         -1.48669892, -0.43769912, -0.21168882,  0.42814002],
        [ 0.51748683,  0.59524486, -0.68714554,  2.20128565,
          0.44015893, -0.09445714,  0.7040363 ,  0.23659022],
        [-2.29931124,  1.18426827, -0.21885241, -1.47192856,
          0.03409908,  0.67508248,  1.62303855,  0.99415627],
        [ 0.66801546,  0.66965841,  1.09986398, -2.59776937,
          1.23635842, -0.18333878,  0.10265375,  0.69760225],
        [ 0.38795999,  0.9464399 ,  1.52599296,  0.77788031,
         -0.06586459, -1.65681846, -0.0908898 ,  0.88940213],
        [-2.00502436, -0.10922257,  0.50868888,  0.86469114,
          1.17830511,  1.18964849,  0.1169976 , -0.21275078]],

       [[ 0.01767338, -0.81945681, -0.40892072, -0.53749856,
          0.08168593, -0.89171152,  2.37348366,  0.04409203],
        [ 0.13913591,  0.51321328, -1.08376693,  0.33096317,
         -1.14103887, -2.01325719,  0.51668939, -2.84832889],
        [ 1.4129704 , -0.92525347, -0.6453766 ,  0.68522758,
          0.03131367, -0.46162143, -1.27124744,  0.4153572 ],
        [ 1.23381012,  1.6863634 , -0.15390508,  0.10693391,
         -2.14823988,  0.77199668,  0.55110515, -0.11387667],
        [ 0.31687054, -0.81740667, -0.96464585,  0.71527462,
          0.89933803, -0.48189178, -0.48778638,  1.06112923],
        [ 0.14866407,  2.36802607,  0.82435356, -0.70566229,
          0.02882325, -0.36668337,  0.09833968,  0.48514864],
        [-1.03096173, -0.62335341,  0.07595689,  0.49099691,
         -0.89083478, -2.13574804,  0.64916785, -0.21457675],
        [ 0.94125089, -0.55449324, -0.19988925,  0.97279036,
          1.94446016,  0.72757272, -0.36140076,  0.95048376]],

       [[ 1.08464023, -1.43503022, -0.79268175,  0.15833147,
         -1.00942184, -0.20671899,  3.02758132, -0.77227674],
        [-0.16117183, -2.26982722, -0.80643034,  0.44940424,
         -0.28004538, -1.9367436 ,  1.29504237,  0.80607537],
        [-0.31447784, -1.86829879, -0.57359464, -0.36466995,
          0.44944582,  1.1431109 ,  0.87503997, -0.69844446],
        [-0.28845718,  0.48023546,  0.46116078,  0.04303454,
          0.08851692,  0.70143801, -2.12962006,  0.0483929 ],
        [-0.01298483, -0.42451359, -0.34897219, -0.40097738,
          2.48541712,  0.217042  , -0.4066374 , -0.94632225],
        [-0.08000587, -0.24372851,  0.01553562,  0.13007874,
          0.85210397,  0.15591757,  0.40225916,  1.69046415],
        [-0.16962411,  1.6228357 , -0.00882255, -1.15471855,
          0.47547434,  0.76355535,  1.6454398 , -0.44044622],
        [-0.46917485, -0.30881452,  0.51917242,  0.62891035,
          0.43171502, -1.17627572,  0.54626833,  1.54324932]],

       [[ 0.2631188 , -2.10952914, -0.59939373,  0.99869393,
          1.96251543,  1.19640179, -0.52179783, -0.64003623],
        [ 0.59314603,  0.71623818,  0.26067409, -1.07240095,
         -1.10854336, -0.50157224,  0.53363211,  0.32696387],
        [-2.4429711 , -0.33434927,  0.35477733, -0.2799178 ,
         -1.83213787, -1.05275551,  0.45385477, -0.84172092],
        [-0.90037698,  2.61832794,  0.96116408,  0.00863791,
          0.44594695, -0.10289984, -1.11961556,  0.61325739],
        [-0.19511801,  1.56005075, -1.10266249, -2.06639657,
          0.74513269, -0.06719751, -1.67425664, -0.27470891],
        [ 0.24131049,  0.32691232, -0.95188948,  2.33751429,
          0.61678244,  0.30155079,  0.65149343, -0.69018639],
        [ 1.05807557,  2.11345856, -0.29919458,  0.06942353,
          1.2342043 ,  1.59519001,  0.38052   , -0.4358339 ],
        [-0.54211133, -0.13275926, -0.68634396, -0.5897906 ,
          0.33063317,  1.12675884, -1.66919356, -0.78223456]]] 
  
K = 100
  
print(pClosest(points, K)) 

SyntaxError: ignored

In [0]:
K=np.random.randn(100,1,2)
K


array([[[-1.80293691e+00,  1.24716731e+00]],

       [[ 3.05318670e-01,  7.16337432e-01]],

       [[-5.91554048e-01, -1.11418783e+00]],

       [[-2.42128471e+00, -2.06293834e+00]],

       [[ 4.59722272e-01,  6.24186001e-01]],

       [[ 2.82653674e-01,  1.70384912e+00]],

       [[ 2.20342815e+00,  1.63814892e+00]],

       [[ 7.49307238e-01, -8.41790068e-02]],

       [[-2.60799795e-01, -1.61088166e+00]],

       [[ 1.59440720e-01,  6.64768550e-02]],

       [[-6.98888241e-01, -5.80346674e-01]],

       [[-8.37992030e-02, -3.97487762e-01]],

       [[ 1.27720977e+00,  1.69140772e+00]],

       [[-1.96602159e+00,  6.03078893e-01]],

       [[ 4.13921445e-01, -4.77456849e-01]],

       [[-4.76093260e-01, -6.45250581e-03]],

       [[ 4.48988730e-01, -2.16397167e-01]],

       [[ 1.90064492e+00,  1.61300326e-01]],

       [[ 1.84157457e+00,  3.17623965e-01]],

       [[-1.62822703e-01,  1.03076642e+00]],

       [[ 1.58925290e+00, -1.42011780e-01]],

       [[ 3.48362795e-01, -5.36890

In [0]:
a=np.random.randn(50,2)
a
b=(a*a).copy()
b
t=np.empty((50),float)
t[:]=b.sum(axis=1)
d=np.argsort(t)
d[40:50]
print(a[d[40:50]])

[[-1.59887716  0.48802779]
 [ 0.87328994  1.46595691]
 [-1.33570712 -1.15330872]
 [ 1.81926167  0.09005409]
 [ 0.68637184  1.70132978]
 [ 0.97890683 -1.58266441]
 [ 1.96617634  0.63578193]
 [-1.91849358 -0.95028605]
 [ 2.16777733 -0.52181328]
 [-1.63725931  1.78503636]]


In [0]:
m=np.random.randn(8,8,8)
m


In [0]:
type()

TypeError: ignored

In [0]:
def pClosest(points, K): 
  
    points.sort(key = lambda K: K[0]**2 + K[1]**2) 
  
    return points[:K] 
  
# Driver program 
points = [[[[-0.92021415,  0.80038559]],

       [[-1.90271923, -1.03938641]],

       [[-1.64984987,  0.49626057]],

       ...,

       [[-1.30709478, -0.61901144]],

       [[-0.36520091, -0.64695998]],

       [[-1.49913979, -0.04305217]]]] 
  
K = 100
  
print(pClosest(points, K)) 

TypeError: ignored

In [0]:
def pClosest(points, K): 
  
    points.sort(key = lambda K: K[0]**2 + K[1]**2) 
  
    return points[:K] 
  
# Driver program 
points = [[3, 3], [5, -1], [-2, 4]] 
  
K = 2
  
print(pClosest(points, K)) 

In [0]:
point=np.random.randn(100,2)

In [0]:
import numpy as np
point=np.random.randn(100,2)
origin=np.sqrt(np.sum(point*point, axis=1))
point[origin.argsort()][:10]

array([[ 0.14277201, -0.02344243],
       [-0.12371133, -0.0753815 ],
       [ 0.06778155,  0.1647291 ],
       [ 0.06182762,  0.20529308],
       [-0.21728527,  0.0827856 ],
       [ 0.17357773,  0.15600036],
       [ 0.3561115 , -0.07278324],
       [-0.40713351, -0.12066428],
       [ 0.51982134, -0.02210713],
       [ 0.19730868, -0.50979897]])

In [0]:
mask=origin<=1

In [0]:
point[mask]

array([[ 0.14710114,  0.84389575],
       [ 0.19730868, -0.50979897],
       [-0.24302676,  0.66488067],
       [ 0.78902652, -0.45260872],
       [-0.83089409, -0.2671523 ],
       [ 0.06778155,  0.1647291 ],
       [ 0.14277201, -0.02344243],
       [-0.79157762, -0.40075056],
       [-0.5451628 , -0.20543087],
       [ 0.60457149, -0.34503988],
       [-0.7235675 ,  0.60651313],
       [-0.73855194, -0.6266347 ],
       [-0.37470958, -0.52715596],
       [ 0.51982134, -0.02210713],
       [ 0.91668875,  0.1003422 ],
       [-0.59060919,  0.60207473],
       [-0.64297843, -0.67977628],
       [-0.36349592, -0.90801218],
       [-0.38109039, -0.81119811],
       [ 0.27260412, -0.62192503],
       [-0.5554224 ,  0.14258539],
       [-0.15751763, -0.7750681 ],
       [ 0.20131212, -0.61916369],
       [-0.21728527,  0.0827856 ],
       [-0.84256524, -0.37546741],
       [-0.2665685 ,  0.77184473],
       [-0.01469565, -0.85954011],
       [ 0.35276172, -0.47746711],
       [ 0.77524737,

In [0]:
point[mask].shape

(39, 2)

In [0]:
mask

array([False, False,  True, False,  True, False, False,  True, False,
        True, False,  True,  True,  True,  True, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True,  True,  True, False, False,
        True,  True, False, False, False, False, False, False, False,
       False,  True, False,  True,  True,  True, False, False,  True,
       False, False, False, False,  True,  True, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
        True, False,  True, False,  True,  True, False, False, False,
       False, False,  True,  True, False,  True, False, False,  True,
       False])

In [0]:
point=np.random.uniform(-1,1,(100,2))

In [0]:
origin=np.sqrt(np.sum(point*point,axis=1))

In [0]:
mask=origin<=1

In [0]:
point[mask].shape[0]

81

In [0]:
81/100*4

3.24

In [0]:
point=np.random.uniform(-1,1(1000,2))


TypeError: ignored

In [0]:
m=np.random.randint(5,9, (8,8,8))
m

array([[[7, 5, 7, 7, 6, 6, 6, 5],
        [6, 7, 6, 8, 5, 5, 5, 5],
        [7, 5, 8, 6, 8, 8, 7, 5],
        [6, 5, 5, 6, 6, 7, 6, 6],
        [7, 7, 5, 5, 8, 7, 7, 8],
        [8, 5, 7, 5, 5, 5, 8, 6],
        [8, 8, 5, 8, 8, 6, 8, 5],
        [7, 7, 7, 6, 8, 6, 6, 7]],

       [[5, 5, 8, 8, 7, 6, 8, 7],
        [8, 5, 5, 8, 7, 5, 8, 8],
        [8, 8, 6, 6, 5, 6, 5, 8],
        [7, 8, 7, 6, 6, 6, 5, 6],
        [8, 6, 6, 6, 6, 5, 8, 5],
        [8, 7, 7, 8, 6, 8, 6, 5],
        [5, 6, 5, 7, 5, 6, 7, 5],
        [7, 8, 8, 8, 8, 6, 7, 5]],

       [[7, 6, 6, 6, 8, 7, 6, 7],
        [5, 6, 5, 8, 7, 5, 5, 8],
        [5, 5, 6, 6, 6, 6, 7, 7],
        [6, 8, 6, 7, 6, 5, 8, 7],
        [8, 5, 5, 7, 6, 5, 7, 6],
        [7, 7, 8, 5, 8, 5, 5, 8],
        [7, 6, 5, 6, 5, 7, 7, 7],
        [6, 8, 8, 7, 8, 8, 5, 7]],

       [[6, 7, 6, 7, 7, 7, 5, 6],
        [5, 5, 6, 6, 7, 8, 5, 6],
        [7, 7, 7, 5, 7, 6, 7, 6],
        [6, 5, 8, 7, 7, 6, 5, 7],
        [8, 8, 6, 7, 7, 8, 5, 7],
        

In [0]:
g=np.random.randint(0,5, (5,5))
h=np.random.randint(0,5, (5,5))
i=np.dot(g,h)
i

array([[23, 43, 37, 39, 16],
       [14, 31, 24, 28, 11],
       [15, 21, 16, 10, 12],
       [20, 37, 34, 26, 19],
       [14, 25, 18, 18, 11]])

In [0]:
np.diag(i)

array([23, 31, 16, 26, 11])

In [0]:
q=np.random.randint(0,9,(3,3))
q
mask=z>5
mask

array([[[False, False]],

       [[False, False]],

       [[False, False]],

       ...,

       [[False, False]],

       [[False, False]],

       [[False, False]]])

In [0]:
np.logical_not(mask,mask)

array([[[ True,  True]],

       [[ True,  True]],

       [[ True,  True]],

       ...,

       [[ True,  True]],

       [[ True,  True]],

       [[ True,  True]]])

In [0]:
arr1=np.random.randn(4,4)

In [0]:
arr1

array([[-2.27897459, -0.14411204,  1.06828422,  0.59030218],
       [-0.14558005, -0.21117647, -0.85033275,  0.02771565],
       [ 0.56327487,  1.06449673, -0.88350339, -0.50516618],
       [-0.10895324,  0.37304903, -0.20641733, -1.84854332]])

In [0]:
np.where(arr1>0, 2, -2)

array([[-2, -2,  2,  2],
       [-2, -2, -2,  2],
       [ 2,  2, -2, -2],
       [-2,  2, -2, -2]])

In [0]:
np.where(arr1>0, 'rofl', 'lol')

array([['lol', 'lol', 'rofl', 'rofl'],
       ['lol', 'lol', 'lol', 'rofl'],
       ['rofl', 'rofl', 'lol', 'lol'],
       ['lol', 'rofl', 'lol', 'lol']], dtype='<U4')

In [0]:
w=np.random.randint(0,9, (5,5,5))


In [0]:
np.sum(w,axis=1)

array([[17, 22, 21, 13, 10],
       [18, 20, 22, 17, 19],
       [13, 30, 18, 19, 20],
       [21, 21, 23, 21, 27],
       [24, 12, 21, 12, 12]])

In [0]:
np.sum(w,axis=2)

array([[17, 13, 19, 16, 18],
       [22, 10, 18, 15, 31],
       [16, 17, 22, 20, 25],
       [25, 22, 25, 14, 27],
       [17, 15, 14, 14, 21]])

In [0]:
np.mean(w)

3.784

In [0]:
np.sort(w)

array([[[0, 1, 3, 5, 8],
        [0, 1, 2, 5, 5],
        [2, 3, 4, 4, 6],
        [1, 2, 2, 3, 8],
        [0, 2, 4, 5, 7]],

       [[1, 2, 5, 6, 8],
        [0, 0, 1, 4, 5],
        [0, 0, 5, 6, 7],
        [1, 1, 2, 5, 6],
        [4, 5, 7, 7, 8]],

       [[1, 1, 4, 5, 5],
        [0, 0, 3, 7, 7],
        [2, 2, 4, 7, 7],
        [0, 1, 5, 7, 7],
        [1, 4, 5, 7, 8]],

       [[1, 5, 5, 7, 7],
        [1, 3, 4, 7, 7],
        [3, 4, 4, 7, 7],
        [1, 1, 2, 3, 7],
        [4, 4, 5, 6, 8]],

       [[1, 2, 3, 4, 7],
        [1, 1, 4, 4, 5],
        [0, 0, 2, 4, 8],
        [1, 2, 2, 2, 7],
        [1, 2, 4, 7, 7]]])

In [0]:
r=np.random.randint(0,9, (5,5))

In [0]:
np.sort(r)

array([[2, 2, 2, 5, 8],
       [0, 0, 1, 2, 4],
       [0, 0, 5, 6, 7],
       [0, 2, 6, 7, 8],
       [0, 1, 7, 8, 8]])

In [0]:
r.sort(0)
r

array([[0, 0, 0, 2, 0],
       [1, 0, 0, 2, 1],
       [2, 2, 6, 4, 2],
       [7, 7, 6, 5, 5],
       [8, 8, 8, 7, 8]])

In [0]:
np.unique(r)

array([0, 1, 2, 4, 5, 6, 7, 8])

In [0]:
np.intersect1d(z,r)

array([], dtype=float64)

In [0]:
np.union1d(z,r)

array([-3.20426302, -3.1992962 , -2.90813344, ...,  6.        ,
        7.        ,  8.        ])

In [0]:
np.save('iitk_pydata_RajatVerma_Day_03.py',w)

In [0]:
np.load('iitk_pydata_RajatVerma_Day_03.py',w)

FileNotFoundError: ignored

In [0]:
!pwd

/content


In [0]:
import pandas as pd #pandas as ordered dictionary

In [0]:
z=pd.Series([1,2,3,4])

In [0]:
z*2

0    2
1    4
2    6
3    8
dtype: int64

In [0]:
np.exp(z)

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

In [0]:
z[z>2]

2    3
3    4
dtype: int64

In [0]:
1 in z

True

In [0]:
'x' in z

False

In [0]:
z.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [0]:
z.notnull()

0    True
1    True
2    True
3    True
dtype: bool

In [0]:
u=pd.Series([1,2,3])
v=pd.Series([a,b,c])
i=u+v
i
pip install Tkinter

SyntaxError: ignored

In [0]:
pip install Tkinter

  ERROR: Could not find a version that satisfies the requirement Tkinter (from versions: none)
ERROR: No matching distribution found for Tkinter


In [0]:
import tkinter as tk
from tkinter import *

root = tk()
root.title('Model Definition')
root.geometry('{}x{}'.format(460, 350))

# create all of the main containers
top_frame = frame(root, bg='cyan', width=450, height=50, pady=3)
center = frame(root, bg='gray2', width=50, height=40, padx=3, pady=3)
btm_frame = frame(root, bg='white', width=450, height=45, pady=3)
btm_frame2 = frame(root, bg='lavender', width=450, height=60, pady=3)

# layout all of the main containers
root.grid_rowconfigure(1, weight=1)
root.grid_columnconfigure(0, weight=1)

top_frame.grid(row=0, sticky="ew")
center.grid(row=1, sticky="nsew")
btm_frame.grid(row=3, sticky="ew")
btm_frame2.grid(row=4, sticky="ew")

# create the widgets for the top frame
model_label = label(top_frame, text='Model Dimensions')
width_label = label(top_frame, text='Width:')
length_label = label(top_frame, text='Length:')
entry_W = entry(top_frame, background="pink")
entry_L = entry(top_frame, background="orange")

# layout the widgets in the top frame
model_label.grid(row=0, columnspan=3)
width_label.grid(row=1, column=0)
length_label.grid(row=1, column=2)
entry_W.grid(row=1, column=1)
entry_L.grid(row=1, column=3)

# create the center widgets
center.grid_rowconfigure(0, weight=1)
center.grid_columnconfigure(1, weight=1)

ctr_left = frame(center, bg='blue', width=100, height=190)
ctr_mid = frame(center, bg='yellow', width=250, height=190, padx=3, pady=3)
ctr_right = frame(center, bg='green', width=100, height=190, padx=3, pady=3)

ctr_left.grid(row=0, column=0, sticky="ns")
ctr_mid.grid(row=0, column=1, sticky="nsew")
ctr_right.grid(row=0, column=2, sticky="ns")
root.mainloop()

TypeError: ignored

In [0]:
data = {
   'state':['Ohio','Nevada'],
    'year':[2001,2009]
}
frame = pd.DataFrame(data)
frame

state  year
0    Ohio  2001
1  Nevada  2009

In [0]:
frame['income_cat']=pd.DataFrame([100,200])
frame
pd.DataFrame(np.random.randn(5,5))


ValueError: ignored

In [0]:
pd.DataFrame(np.random.randn(5,5), columns=['x','y','z','a','b'])

x         y         z         a         b
0  0.917288 -0.417236  1.701507  0.367854  1.805115
1  0.477538  0.629548  0.542555 -1.560405 -1.056412
2 -0.994619  0.648058 -1.290244 -0.086381  0.033334
3  1.371032  1.122511 -0.486454 -0.476996 -0.722776
4  0.034724  1.122468 -1.491246  0.892830 -1.647459

In [0]:
data = [
    {'fname':'Avneesh', 'lname':'Jain', 'age':44},
    {'fname':'Rajat', 'lname':'Verma'}
]
pd.DataFrame(data)


age    fname  lname
0  44.0  Avneesh   Jain
1   NaN    Rajat  Verma

In [0]:
z=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep='|')
z

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
7          8   36      M  administrator    05201
8          9   29      M        student    01002
9         10   53      M         lawyer    90703
10        11   39      F          other    30329
11        12   28      F          other    06405
12        13   47      M       educator    29206
13        14   45      M      scientist    55106
14        15   49      F       educator    97301
15        16   21      M  entertainment    10309
16        17   30      M     programmer    06355
17        18   35      F          other    37212
18        19   40      M      librarian    02138
19        20   42      F      homemaker    95660
20        21   26      M         writer    30068
21        22   25      M         writer    40206
22        23   30      F         artist    48197
23        24   21      F         artist    94533
24        25   39      M       engineer    55107
25        26   49      M       engineer    21044
26        27   40      F      librarian    30030
27        28   32      M         writer    55369
28        29   41      M     programmer    94043
29        30    7      M        student    55436
..       ...  ...    ...            ...      ...
913      914   44      F          other    08105
914      915   50      M  entertainment    60614
915      916   27      M       engineer    N2L5N
916      917   22      F        student    20006
917      918   40      M      scientist    70116
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [0]:
y=pd

In [0]:
from tkinter import *
 
root = Tk()
topFrame = Frame(root)
topFrame.pack(side=TOP)
 
middleFrame = Frame(root)
middleFrame.pack(side=RIGHT)
 
bottomFrame = Frame(root, bg="green")
bottomFrame.pack(side=BOTTOM)
 
topFrame_Label = Label(topFrame, text="Welcome to Python GUI(Top Frame)")
topFrame_Label.pack()
 
middleFrame_Label = Label(middleFrame, text="Welcome to Python GUI(Middle Frame)")
middleFrame_Label.pack()
 
bottomFrame_Label = Label(bottomFrame, text="Welcome to Python GUI(Bottom Frame)")
bottomFrame_Label.pack()
theButton = Button(bottomFrame, text="Button", fg="red", bg="black")
theButton.pack()
root.minsize(400, 400)
root.mainloop()

TclError: ignored